### ISSUE TITLE
Looks like we failed to generate your Zim file! 

### ISSUE THREAD

**Issue by samuk** [openzim/zip2zim#13]
The error is
"Usually this is caused by a broken config.json file."

This is the zip I'm uploading: https://upload.disroot.org/r/PdfBk82x#qul454xv5N01oinH8/R4sLxdbdHFu6kb/75Ya5cdtdw=

**Comment by kelson42** [comment]
@samuk As far as I can see, there is not `config.json` file.

**Comment by ISNIT0** [comment]
Hi @samuk,
The zip file seems to have a folder inside it (called mustard2).
Zip2Zim expects the zip file to have either an `index.html` file or `config.json` in the root.

Here is a fixed zip for you:
https://framadrop.org/r/_dDQKXxMsD#fJePKS2Kxl5b/D0ZAebx2sgWUIJhAZWjTtSNfr/fZWA=
