### ISSUE TITLE
How files are cleaned-up?

### ISSUE THREAD

**Issue by kelson42** [openzim/zip2zim#6]
I mean:
* original ZIP files
* create ZIM files

**Comment by ISNIT0** [comment]
Not quite sure what you mean

**Comment by kelson42** [comment]
ZIP and ZIM files which are not used anymore should be deleted. What is the strategy for each of them?

**Comment by ISNIT0** [comment]
Ahh, I see.
They get deleted after 10 minutes I believe.
https://github.com/openzim/zip2zim/blob/master/index.ts#L16

**Comment by ISNIT0** [comment]
Or 100 Minutes

**Comment by kelson42** [comment]
@ISNIT0 Thx, that is good (for now) :)
